version: '3.8'

services:
  database:
    image: ${DOCKER_USER}/innovatech-data:latest
    container_name: data_service
    restart: always
    environment:
      # Definimos la contraseña del superusuario root
      - MYSQL_ROOT_PASSWORD=${{ secrets.DB_PASSWORD}}
      - MYSQL_DATABASE=proyecto_db
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=${{ secrets.DB_PASSWORD }}
    ports:
      - "3306:3306"
    volumes:
      - db_persistence:/var/lib/mysql
    networks:
      - deploy-net

networks:
  deploy-net:
    external: true

volumes:
  db_persistence:

  environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=proyecto_db
      # IMPORTANTE: Borra o comenta estas líneas:
      # - MYSQL_USER=root  <-- ESTA ES LA QUE MATA EL CONTENEDOR
      # - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}