version: '3.8'

services:
  database:
    image: ${DOCKER_USER}/innovatech-data:latest
    container_name: data_service
    restart: always
    environment:
      # Credenciales de MySQL
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      # Configuración del charset
    ports:
      - "3306:3306"
    volumes:
      - db_persistence:/var/lib/mysql
    networks:
      - deploy-net

networks:
  deploy-net:
    external: true

volumes:
  db_persistence:
