version: '3.8'

services:
  database:
    image: ${DOCKER_USER}/innovatech-data:latest
    container_name: data_service
    restart: always
    environment:
      - MYSQL_DATABASE=proyecto_db
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db_persistence:/var/lib/mysql
    networks:
      - deploy-net

networks:
  deploy-net:
    external: true

volumes:
  db_persistence: